//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { BaseApiClient } from '.';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class ForecastClient extends BaseApiClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        super();
        this.http = http;
        this.baseUrl = baseUrl ?? this.getBaseUrl("https://localhost:44375");
    }

    /**
     * @return OK
     */
    forecast_Get(lat: number, lon: number): Observable<ForecastDto> {
        let url_ = this.baseUrl + "/api/Forecast?";
        if (lat === undefined || lat === null)
            throw new Error("The parameter 'lat' must be defined and cannot be null.");
        else
            url_ += "lat=" + encodeURIComponent("" + lat) + "&";
        if (lon === undefined || lon === null)
            throw new Error("The parameter 'lon' must be defined and cannot be null.");
        else
            url_ += "lon=" + encodeURIComponent("" + lon) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.transformResult(url_, response_, (r) => this.processForecast_Get(r as any));
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processForecast_Get(r as any));
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ForecastDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ForecastDto>;
        }));
    }

    protected processForecast_Get(response: HttpResponseBase): Observable<ForecastDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ForecastDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable()
export class HomeClient extends BaseApiClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        super();
        this.http = http;
        this.baseUrl = baseUrl ?? this.getBaseUrl("https://localhost:44375");
    }

    /**
     * @return OK
     */
    home_Index(): Observable<any> {
        let url_ = this.baseUrl + "/api/home";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.transformResult(url_, response_, (r) => this.processHome_Index(r as any));
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processHome_Index(r as any));
                } catch (e) {
                    return _observableThrow(e) as any as Observable<any>;
                }
            } else
                return _observableThrow(response_) as any as Observable<any>;
        }));
    }

    protected processHome_Index(response: HttpResponseBase): Observable<any> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class ForecastDto implements IForecastDto {
    location?: LocationDto | undefined;
    dates?: DateForecast[] | undefined;

    constructor(data?: IForecastDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.location = _data["Location"] ? LocationDto.fromJS(_data["Location"]) : <any>undefined;
            if (Array.isArray(_data["Dates"])) {
                this.dates = [] as any;
                for (let item of _data["Dates"])
                    this.dates!.push(DateForecast.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ForecastDto {
        data = typeof data === 'object' ? data : {};
        let result = new ForecastDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Location"] = this.location ? this.location.toJSON() : <any>undefined;
        if (Array.isArray(this.dates)) {
            data["Dates"] = [];
            for (let item of this.dates)
                data["Dates"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IForecastDto {
    location?: LocationDto | undefined;
    dates?: DateForecast[] | undefined;
}

export class LocationDto implements ILocationDto {
    name?: string | undefined;
    timeZone?: string | undefined;
    currentTime?: DateTimeDto | undefined;

    constructor(data?: ILocationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            this.timeZone = _data["TimeZone"];
            this.currentTime = _data["CurrentTime"] ? DateTimeDto.fromJS(_data["CurrentTime"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LocationDto {
        data = typeof data === 'object' ? data : {};
        let result = new LocationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        data["TimeZone"] = this.timeZone;
        data["CurrentTime"] = this.currentTime ? this.currentTime.toJSON() : <any>undefined;
        return data;
    }
}

export interface ILocationDto {
    name?: string | undefined;
    timeZone?: string | undefined;
    currentTime?: DateTimeDto | undefined;
}

export class DateForecast implements IDateForecast {
    date?: DateTimeDto | undefined;
    hours?: HourForecast[] | undefined;

    constructor(data?: IDateForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["Date"] ? DateTimeDto.fromJS(_data["Date"]) : <any>undefined;
            if (Array.isArray(_data["Hours"])) {
                this.hours = [] as any;
                for (let item of _data["Hours"])
                    this.hours!.push(HourForecast.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DateForecast {
        data = typeof data === 'object' ? data : {};
        let result = new DateForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Date"] = this.date ? this.date.toJSON() : <any>undefined;
        if (Array.isArray(this.hours)) {
            data["Hours"] = [];
            for (let item of this.hours)
                data["Hours"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IDateForecast {
    date?: DateTimeDto | undefined;
    hours?: HourForecast[] | undefined;
}

export class DateTimeDto implements IDateTimeDto {
    year?: number | undefined;
    month?: number | undefined;
    day?: number | undefined;
    hour?: number | undefined;
    minute?: number | undefined;

    constructor(data?: IDateTimeDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.year = _data["Year"];
            this.month = _data["Month"];
            this.day = _data["Day"];
            this.hour = _data["Hour"];
            this.minute = _data["Minute"];
        }
    }

    static fromJS(data: any): DateTimeDto {
        data = typeof data === 'object' ? data : {};
        let result = new DateTimeDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Year"] = this.year;
        data["Month"] = this.month;
        data["Day"] = this.day;
        data["Hour"] = this.hour;
        data["Minute"] = this.minute;
        return data;
    }
}

export interface IDateTimeDto {
    year?: number | undefined;
    month?: number | undefined;
    day?: number | undefined;
    hour?: number | undefined;
    minute?: number | undefined;
}

export class HourForecast implements IHourForecast {
    time?: DateTimeDto | undefined;
    temperature?: number | undefined;
    windSpeed?: number | undefined;
    windDirection?: string | undefined;
    isRain?: boolean | undefined;
    isSnow?: boolean | undefined;

    constructor(data?: IHourForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.time = _data["Time"] ? DateTimeDto.fromJS(_data["Time"]) : <any>undefined;
            this.temperature = _data["Temperature"];
            this.windSpeed = _data["WindSpeed"];
            this.windDirection = _data["WindDirection"];
            this.isRain = _data["IsRain"];
            this.isSnow = _data["IsSnow"];
        }
    }

    static fromJS(data: any): HourForecast {
        data = typeof data === 'object' ? data : {};
        let result = new HourForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Time"] = this.time ? this.time.toJSON() : <any>undefined;
        data["Temperature"] = this.temperature;
        data["WindSpeed"] = this.windSpeed;
        data["WindDirection"] = this.windDirection;
        data["IsRain"] = this.isRain;
        data["IsSnow"] = this.isSnow;
        return data;
    }
}

export interface IHourForecast {
    time?: DateTimeDto | undefined;
    temperature?: number | undefined;
    windSpeed?: number | undefined;
    windDirection?: string | undefined;
    isRain?: boolean | undefined;
    isSnow?: boolean | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}